### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by ahtisham49** [phen0menon/blum-autoclicker#11]
Traceback (most recent call last):
  File "C:\Users\LENOVO\Desktop\blum-autoclicker-main\main.py", line 12, in <module>
    from ultralytics import YOLO
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\data\base.py", line 15, in <module>
    from torch.utils.data import Dataset
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\LENOVO\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by DevelSnap** [comment]
install python 3.8.8
in file requirements.txt change string numpy==1.21.6
follow further instructions

**Comment by AgentJT1** [comment]
Пришлось повозиться 2 вечера, чтобы это всё заработало, обновите пожалуйста инструкцию, я до этого с python не сталкивался, поэтому было тяжело.
Надо устанавливать python с установленной галочкой "Add Python to PATH" перед установкой. 3.8 версий много, хорошо в этом комментарии увидел про 3.8.8, так же пришлось подправить файл requirements.txt изменив значение на то, как описали numpy==1.23.0 и только после этого выполнять 
pip install -r requirements.txt
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
python main.py
Если до этого уже установили, то сначала удалить и потом заново ставить
pip uninstall -r requirements.txt
pip uninstall torch torchvision torchaudio
